### ISSUE TITLE
Demo Code in the documentation is not working 

### ISSUE THREAD

**Issue by Pavankunchala** [Cryptolens/cryptolens-python#52] opened 2022-08-05 07:58 UTC
Here is my code 
```
    
from licensing.models import *
from licensing.methods import Key, Helpers
import requests
import ssl

# WyI1MjY3NDUiLCJlS3NUQjkxTkk1TWhyS3dnVGdKaDZkM0VpcnRLZmtjRVFxMGlmem5YIl0=

# fixes SSL cerift errors
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

RSAPubKey = "<RSAKeyValue><Modulus>sGbvxwdlDbqFXOMlVUnAF5ew0t0WpPW7rFpI5jHQOFkht/326dvh7t74RYeMpjy357NljouhpTLA3a6idnn4j6c3jmPWBkjZndGsPL4Bqm+fwE48nKpGPjkj4q/yzT4tHXBTyvaBjA8bVoCTnu+LiC4XEaLZRThGzIn5KQXKCigg6tQRy0GXE13XYFVz/x1mjFbT9/7dS8p85n8BuwlY5JvuBIQkKhuCNFfrUxBWyu87CFnXWjIupCD2VO/GbxaCvzrRjLZjAngLCMtZbYBALksqGPgTUN7ZM24XbPWyLtKPaXF2i4XRR9u6eTj5BfnLbKAU5PIVfjIS+vNYYogteQ==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>"
auth = "WyIyNTU1IiwiRjdZZTB4RmtuTVcrQlNqcSszbmFMMHB3aWFJTlBsWW1Mbm9raVFyRyJd=="

result = Key.activate(token=auth,\
                   rsa_pub_key=RSAPubKey,\
                   product_id=16229, \
                   key="IORSI-OBUYU-FATEO-HHXJT",\
                   machine_code= None)

if result[0] == None:
    # an error occurred or the key is invalid or it cannot be activated
    # (eg. the limit of activated devices was achieved)
    print("The license does not work: {0}".format(result[1]))
else:
    # everything went fine if we are here!
    print("The license is valid!")
    license_key = result[0]
    print("Feature 1: " + str(license_key.f1))
    print("License expires: " + str(license_key.expires))

```
Do let me know where I am making the mistake

**Comment by artemlos** [comment] 2022-08-05 14:22
@Pavankunchala thanks for the question & feedback!

When I tried to call the API using the access token that is being used, I received "Unable to authenticate" error, which means that the access token does not exist. Most likely, there is a typo somewhere. We have more information on how to troubleshoot API errors on the following page: https://help.cryptolens.io/faq/index#troubleshooting-api-errors

More specifically, this is the request that can be used to reproduce the error.
```
https://api.cryptolens.io/api/key/activate?token=WyIyNTU1IiwiRjdZZTB4RmtuTVcrQlNqcSszbmFMMHB3aWFJTlBsWW1Mbm9raVFyRyJd==
```

The documentation code uses demo tokens as an example. You would need to replace the token, RSA Public Key, the Product Id and the license key, for the code to work.

I will close the issue here on GitHub, since it's related to the platform. I would recommend to send us additional questions to support@cryptolens.io or through the chat box, especially if the code includes access tokens and other customer specific parameters. This to ensure that no sensitive parameters are published publicly.

Please let us know should you have any other questions - we would be happy to help!

**Closed as completed by artemlos** 2022-08-05 14:22 UTC

**Comment by Pavankunchala** [comment] 2022-08-05 21:27
I have created a new ID and Key for a new product
How can I create new RSA public key and token

Edit 1
Figured out how to create a new token 
but am getting a different error now


```
The license does not work: The signature check failed.
```

**Comment by Pavankunchala** [comment] 2022-08-05 21:57
Had made some changes 
It is working now
