### ISSUE TITLE
Could not contact the server

### ISSUE THREAD

**Issue by ahaseeb7838** [Cryptolens/cryptolens-python#31] opened 2020-09-13 13:00 UTC
Using simple code for verifications of License key and Getting "Could not Contact the Server"

**Comment by artemlos** [comment] 2020-09-21 08:55
@ahaseeb7838 Could you please share the code that you were using that caused this issue?

**Comment by ahaseeb7838** [comment] 2020-09-21 09:02
@artemlos 


`def auth_key():
    key = str(input("Auth KEY: "))
    result = Key.activate(token=auth, rsa_pub_key=RSAPubKey,
                          product_id=7713, key=key, machine_code=Helpers.GetMachineCode())

    if result[0] is None or not Helpers.IsOnRightMachine(result[0]):
        print("The License does not work:{0}".format(result[1]))
        auth_key()
    else:
        print("The License is valid")
        pass`
This is the code, I'm using

**Comment by artemlos** [comment] 2020-09-21 09:18
@ahaseeb7838 Could you please include the access token and RSA Public key as well? The access token should only have access to the Activate method.

**Comment by copterspace** [comment] 2020-09-25 16:03
IMHO, it is not because of connection at all, but because of mistyped verify_SSL field name I corrected in https://github.com/Cryptolens/cryptolens-python/pull/33
Message 'Could not contact the Server' I suppose should also be clarified somehow - that error above was due to the code, nothing about server or connection...

**Comment by artemlos** [comment] 2022-07-28 16:30
It seems like the issue got resolved, so I will close the issue here on GitHub.

In latest versions of the package, we introduced better error handling with more details on the cause of a specific error. I think this could help to resolve the issue in case it still persists.

Please feel free to reopen the issue or reach out to us at support@cryptolens.io.

**Closed as completed by artemlos** 2022-07-28 16:30 UTC
