### ISSUE TITLE
ModuleNotFoundError: No module named 'licensing.models'; 'licensing' is not a package

### ISSUE THREAD

**Issue by BeauRussell** [Cryptolens/cryptolens-python#46] opened 2021-10-04 03:11 UTC
Hi, I'm trying to install and set up a test case in my python application using your package, but I'm getting a weird error. Everything installed correctly, but when I try to run the application I get this error:
"ModuleNotFoundError: No module named 'licensing.models'; 'licensing' is not a package"

**Comment by BeauRussell** [comment] 2021-10-04 03:15
I've tested this through Python 3.9.5 and 3.6.8 both giving the same error so I don't think it has anything to do with my environment

**Comment by artemlos** [comment] 2021-10-05 07:04
@BeauRussell thanks for the question.

I have seen this error message experienced by another client before. I can't remember the exact way it was solved, but it was related to the package not being installed in the correct way. I'm running Python 3.6.10 myself and was not able to reproduce the issue.

Could you please include all commands that you ran to install the package and run the script?

Thanks!
Artem

support@cryptolens.io

**Comment by BeauRussell** [comment] 2021-10-06 00:26
@artemlos Yes I followed exactly what the ReadMe says. All I did was `pip install licensing` and then import it similar to the example. I was able to look in the .venv folders and find the package installed successfully.

**Comment by artemlos** [comment] 2021-10-07 07:56
@BeauRussell Thanks!

Assuming that you are running Python3 and your script is in `test.py`, could you please test the following:

````bash
python3 -m pip install licensing
python3 test.py
````

**Comment by BeauRussell** [comment] 2021-10-07 13:40
@artemlos That is exactly the same thing and as expected produces the same error

**Comment by artemlos** [comment] 2021-10-07 13:43
@BeauRussell Could you please tell me a bit more about the environment where this was executed?

I.e. OS, Python version, etc.

**Comment by BeauRussell** [comment] 2021-10-08 20:08
@artemlos Windows 10, Tested in python virtual environments with both 3.6.8 and 3.9.6

**Comment by artemlos** [comment] 2021-10-11 14:06
@BeauRussell I performed a test with Python 3.9.5 and was initially able to reproduce it in a virtual environment. The problem is in the pip version that is used to install the package. The best way to ensure that right version of pip is being used and that the package is installed inside the virtual environment and not globally (I think that was why I first received the same error message, since I ran the pip command directly).

**Solution**
Below are the steps that I ran that solved the problem:

```bash
python3.9 -m venv venv
source venv/bin/activate
python3 -m pip install licensing
python3 

>>> from licensing.models import *
>>> from licensing.methods import Key, Helpers
```

Since you are using different python versions on the same machine, I would specify the entire python version when running the commands above, for example, instead of `python3`, try with `python3.9.6`

Please let me know if the error would still persist.

**Comment by BeauRussell** [comment] 2021-10-11 15:34
I have the exact same error. I'm using the venv in an integrated terminal through VSCode, so it already sets everything up correctly

**Comment by artemlos** [comment] 2021-10-11 15:56
@BeauRussell Quick question: if you run the commands I described in separate terminal window, does it work or do you still get the same error message?

**Comment by BeauRussell** [comment] 2021-10-11 16:51
Yes

**Comment by artemlos** [comment] 2021-10-11 17:00
Nice to hear that! I will close the issue since the error seems to be resolved. Based on the information, it seems that the error was related to a Python configuration.

If you would have any other questions, please reach out to us here on GitHub or on support@cryptolens.io.

**Closed as completed by artemlos** 2021-10-11 17:00 UTC
